SELECT 
    DAT_VTE,
    NUM_TIC,
    NUM_RGRPCLI,
    LIB_TYPFID_CART,
    NUM_PERSLM_ENT_CRE,
    MNT_TTCDEVETT,
    NUM_ETT,
    LIB_MAGCRT,
    NUM_REG,
    LIB_REG,
    NUM_RGRP,
    LIB_RGRP,
    NUM_ART,
    LIB_ART,
    NUM_RAY,
    LIBNUMRAY,
    NUM_SRAY,
    LIBCODSRAY,
    NUM_TYP,
    LIBCODTYP,
    NUM_STYP,
    LIBCODSTYP
FROM dfdp-lmpt-business-dmart.VENDAS.VENDAS
WHERE 
EXTRACT(YEAR FROM DAT_VTE) IN (2021)